
<?php

$GLOBALS['dataFolder'] = "";
$GLOBALS['bookNodeId'] = 'new';
$GLOBALS['mapMkdoc'] = array();

function mkdoc_book_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
	
	dsm('6666666666666----'.$op);
	//watchdog('Raymond Fu', $op);
	switch($op) {
		case 'presave':
			//dsm($node);
			$viewNid = $node->nid;
			$bookId = mkdoc_nid_getCurrentBookId($viewNid);
			if(!$bookId) {
				break;	
			}
			$content = $node->body;
			$bookValue = mkdoc_book_getBookFolder($bookId);
			//get git repository url
			$bookFolder = $bookValue['bookfolder'];
			$gitRepoUrl = $bookValue['repourl'];
			var_dump($viewNid.'---bookid========'.$bookId);
			$mkdoc = MkDoc::getInstance();
			$datamk = $mkdoc->getMkdocsFromDb($bookId);
			//dsm($datamk);
			$linkNames = $datamk->pagesByLinkName;
			$nodeIds = $datamk->pagesByNodeId;
			$mdLink = $nodeIds[$viewNid]->mdLink;
			////dsm($mdLink);

			updateMdContent($mdLink, $content, $bookFolder, $gitRepoUrl);
			break;

			case 'update':	//update the content of page
				break;

			case 'delete':	//delete a page
				break;

			case 'insert':	//insert a new page
				break;

			case 'alter':	//$node->content array has been rendered
				break;

			case 'view':	

				$viewNid = $node->nid;
				//$bookId = $node->book['bid'];
				//if(!$bookId) {
				//	break;	
				//}

		//		mkdoc_book_getBookOutline($bookId);

				break;
	}
}

function mkdoc_book_form_node_delete_confirm_alter(&$form, &$form_state) {
	dsm('=============mkdoc_book_form_node_delete_confirm_alter');
	dsm($form);
	dsm($form_state);
	//$form['actions']['submit']['#submit'][] = 'mkdoc_book_deletePage';
	//$form['#submit'][] = 'mkdoc_book_deletePage';
	dsm('=end============mkdoc_book_form_node_delete_confirm_alter');
}

function mkdoc_book_deletePage(&$form, $form_state) {
	dsm('===========mkdoc_book_deletePage');
	dsm($form);
	dsm($form_state);
	if($form_state['submitted']) {
		$nodeId = $form_state['values']['nid'];
		dsm('=======deleting node '.$nodeId);
		$node = $form['#parameters'][2];
		$nodeId = $node->nid;
		$bookId = $node->book['bid'];

		mkdoc_book_deletePageImp($bookId, $nodeId);
	}
	dsm('==end=========mkdoc_book_deletePage');
}

function mkdoc_book_deletePageImp($bookId, $nodeId) {
	
	dsm('mkdoc_book_deletePageImp....bookId:'.$bookId.'....nodeId:'.$nodeId);
	$mkdoc = mkdoc_book_getMkDoc($bookId);
	dsm($mkdoc);
	$bookValue = mkdoc_book_getBookFolder($bookId);
	$bookFolder = $bookValue['bookfolder'];
	$gitRepoUrl = $bookValue['repourl'];

	$nodeIds = $mkdoc->pagesByNodeId;
	dsm($nodeIds);
	if(array_key_exists($nodeId, $nodeIds)) {
		$mdName = $nodeIds[$nodeId]->mdLink;

		$baseFolder = getcwd().'/files/gdc-docs/gitdata/';
		$fileName = $baseFolder.$bookFolder.'/docs/'.$mdName;

		dsm('deleteing '.$fileName);
		if(file_exists($fileName)) {
			unlink($fileName);	
			dsm('deleted '.$fileName);
		}
		//remove nodeid from mkdoc, and re-save it
		unset($nodeIds[$nodeId]);

		$linkNames = $mkdoc->pagesByLinkName;
		if(array_key_exists($mdName, $linkNames)) {
			unset($linkNames[$mdName]);	
		}

		$mkdoc->pagesByNodeId = $nodeIds;
		$mkdoc->pagesByLinkName = $linkNames;

		$mkDoc = MkDoc::getInstance();
		$mkDoc->setMkdocsToDb($bookId, $mkdoc, $bookFolder, $gitRepoUrl);

		mkdoc_book_getBookOutline($bookId);
	}

	
}

function mkdoc_book_changePageOutline(&$form, $form_state) {
	dsm('===========mkdoc_book_changePageOutline');
	dsm($form);
	dsm($form_state);
	if($form_state['submitted']) {
		$nodeBook = $form_state['values']['book'];
		dsm('=======changing page node '.$nodeBook['bid']);
		$bookId = $nodeBook['bid'];
		mkdoc_book_getBookOutline($bookId);
	}
	dsm('==end=========mkdoc_book_changePageOutline');
}

function mkdoc_book_changeBook(&$form, $form_state) {
	dsm('===========mkdoc_book_changeBook');
	dsm($form);
	dsm($form_state);
	if($form_state['submitted']) {
		$nodeBook = $form['#node']->book;
		dsm('=======changing page node '.$nodeBook['bid']);
		mkdoc_book_getBookOutline($nodeBook['bid']);
	}
	dsm('==end=========mkdoc_book_changeBook');
}

function mkdoc_book_form_alter(&$form, $form_state, $form_id) {
	dsm('============mkdoc_book_form_alter');
	dsm($form);
	dsm($form_state);
	dsm('======form id: '.$form_id);

	switch($form_id) {
		case 'book_outline_form':
			$form['#submit'][] = 'mkdoc_book_changePageOutline';
			break;

		case 'node_delete_confirm':
			$form['#submit'][] = 'mkdoc_book_deletePage';
			//$form['actions']['submit']['#submit'][] = 'mkdoc_book_deletePage';
			//$form['actions']['submit']['#submit'][] = 'node_delete_confirm_submit';
			break;

		case 'book_admin_edit':
			$form['#submit'][] = 'mkdoc_book_changeBook';
			break;
	}


}

function mkdoc_book_getBookOutline($bookId) {

	$nodeBook = node_load($bookId);
	$menuName = $nodeBook->book['menu_name'];
	//dsm($nodeBook);
	//dsm($menuName);
	$bookValue = mkdoc_book_getBookFolder($bookId);
	$bookFolder = $bookValue['bookfolder'];
	$gitRepoUrl = $bookValue['repourl'];

	$bookStru = menu_tree_all_data($menuName);
	if($bookStru) {
		dsm($bookStru);
		$mkdoc = MkDoc::getInstance();
		$datamk = $mkdoc->getMkdocsFromDb($bookId);
		dsm($datamk);	
		$baseFolder = getcwd().'/files/gdc-docs/gitdata/';
		$bookFolder = $baseFolder.$bookFolder.'/docs/';
		dsm('current book folder======'.$bookFolder);
//		mkdoc_book_removeAllFiles($bookFolder);

		$data = array();
		$newMkdoc = array('pagesByNodeId' => array(), 'pagesByLinkName' => array());
		$ret = mkdoc_book_fetchBookObject(0, $bookStru, $data, $datamk->pagesByNodeId, $bookFolder, '', $newMkdoc);
		//dsm($data);
		dsm($ret);
		dsm(json_encode($ret));

		$datamk->pagesByNodeId = $newMkdoc['pagesByNodeId'];
		$datamk->pagesByLinkName = $newMkdoc['pagesByLinkName'];
		dsm($datamk);
		$bookFolder = $bookValue['bookfolder'];

		$mkdoc->setMkdocsToDb($bookId, $datamk, $bookFolder, $gitRepoUrl);
		$dddd = $mkdoc->getMkdocsFromDb($bookId);
		dsm($dddd);

		mkdoc_book_rebuildFile($ret, $bookId, $datamk);
	}

}

function mkdoc_book_setMkDoc($bookId, $mkdata) {
	$bookValue = mkdoc_book_getBookFolder($bookId);
	$bookFolder = $bookValue['bookfolder'];
	$gitRepoUrl = $bookValue['repourl'];
	
	$mkdoc = MkDoc::getInstance();
	$mkdoc->setMkdocsToDb($bookId, $mkdata, $bookFolder, $gitRepoUrl);
	
}

function mkdoc_book_getMkDoc($bookId) {
	$mkdoc = MkDoc::getInstance();
	$datamk = $mkdoc->getMkdocsFromDb($bookId);
	
	return $datamk;
}

//reconstruct the files based on book outline
//files maybe removed or moved
function mkdoc_book_rebuildFile($yamlObj, $bookId, $mkdoc) {
	
	$bookValue = mkdoc_book_getBookFolder($bookId);
	//get git repository url
	$bookFolder = $bookValue['bookfolder'];
	$gitRepoUrl = $bookValue['repourl'];
	
	mkdoc_book_rebuildFileImp($yamlObj, $mkdoc);

	$yamlContent = json_encode($yamlObj);
	dsm($yamlContent);
	mkdoc_book_updateBook($yamlContent, $bookFolder, $gitRepoUrl);
}

function mkdoc_book_rebuildFileImp($yamlObj, $mkdoc) {
	
	foreach($yamlObj as $name => $obj) {
		
	}
}

function mkdoc_book_removeAllFiles($folder) {

	dsm('remove all files...'.$folder);
	if(is_dir($folder)) {
		array_map(function($value) {
			mkdoc_book_removeAllFiles($value);
			rmdir($value);
		}, glob($folder.'/*', GLOB_ONLYDIR));	
	}
	array_map('unlink', glob($folder."/*"));

}

function mkdoc_book_fetchBookObject($parentId, $bookStructure, &$dataRet, $nodeIds, $bookFolder, $currentFolder, &$newDoc) {
dsm($bookStructure);
dsm($nodeIds);
dsm('current folder---'.$currentFolder);
	$originalFolder = $currentFolder;
	foreach($bookStructure as $name => $obj) {
	
		//dsm('========='.$name);
		//dsm($obj['below']);
		if($obj['below']) {
			//dsm($obj['link']);
			if($obj['link']['plid'] == 0) {
				$nodeId = substr($obj['link']['link_path'], strpos($obj['link']['link_path'], '/') + 1);
				$dataRet['site_name'] = $obj['link']['title'];
				$dataRet['pages'] = array(mkdoc_book_fetchBookObject($nodeId, $obj['below'], $dataRet['pages'], $nodeIds, $bookFolder, $currentFolder, $newDoc));	
			} else {
				//dsm($obj['link']['title']);
				$chapter = $obj['link']['title'];
				if(!is_dir($bookFolder.$chapter)) {
					dsm($bookFolder.$chapter);
					//mkdir($bookFolder.$chapter, 0755, true);	
				}

				$currentFolder = $chapter.'/';
				$title = $obj['link']['title'];
				$dataRet[$title] = array();
				$nodeId = substr($obj['link']['link_path'], strpos($obj['link']['link_path'], '/') + 1);
				if(array_key_exists($nodeId, $nodeIds)) {
					$nodeObj = $nodeIds[$nodeId];
					$oldChapter = $nodeObj->title;//substr($nodeObj->mdLink, 0, strrpos($nodeObj->mdLink, '/'));
					rename($bookFolder.$oldChapter, $bookFolder.$chapter);
					dsm('rename folder from '.$oldChapter.' to  '.$chapter);
				} else {
					mkdir($bookFolder.$chapter, 0755, true);
					dsm('created new folder '.$bookFolder.$chapter);
				}
				$newData = new stdClass();
				$newData->nodeId = $nodeId;
				$newData->parentId = $nodeIds[$nodeId]->parentId;
				$newData->title = $title;
				$newData->mdLink = $nodeIds[$nodeId]->mdLink;
				$newDoc['pagesByNodeId'][$nodeId] = $newData;
				$newDoc['pagesByLinkName'][$title] = $newData;
				$dataRet[$title] = array(mkdoc_book_fetchBookObject($nodeId, $obj['below'], $dataRet[$title], $nodeIds, $bookFolder.$chapter, $currentFolder, $newDoc));	
			}
		} else {
			
			if($obj['link']) {
				
				$nodeId = substr($obj['link']['link_path'], strpos($obj['link']['link_path'], '/') + 1);
				$title = $obj['link']['title'];
				dsm($nodeId);
				dsm($nodeIds);
				if($nodeId) {
					
					$node = node_load($nodeId);
					if(array_key_exists($nodeId, $nodeIds)) {
						$nodeObj = $nodeIds[$nodeId];
						dsm($node);
						dsm($nodeObj->mdLink);
						$linkName = $nodeObj->mdLink;
						if(strrpos($nodeObj->mdLink, '/')) {
							$name = substr($nodeObj->mdLink, strrpos($nodeObj->mdLink, '/') +1);
							$dataRet[$title] = $currentFolder.$name;
							$linkName = $currentFolder.$name;
						} else {
							$name = $nodeObj->mdLink;	
							$dataRet[$title] = $name;
							$linkName = $name;
						}
						
						$nameFile = $name;
						if($bookFolder[strlen($bookFolder)-1] == '/') {
							$nameFile = $bookFolder.$name;
						} else {
							$nameFile = $bookFolder.'/'.$name;	
						}
						$bookFolderTmp = substr($bookFolder, 0, strrpos($bookFolder, '/')+1);
						$oldFile = $bookFolderTmp.$nodeObj->mdLink;
						//unlink($oldFile);
						dsm($nameFile.'------'.$linkName.'-----'.$currentFolder);
						//file_put_contents($nameFile, $node->body);
						dsm('remove file from '.$oldFile.' to  '.$nameFile);
						rename($oldFile, $nameFile);
					} else {
						$linkName = strtolower(str_replace(' ', '-', $title)).'.md';
						$newFile = $bookFolder.'/'.$linkName;
						$linkName = $currentFolder.$linkName;
						dsm('creating new file '.$newFile);
						file_put_contents($newFile, $node->body);
						$dataRet[$title] = $linkName;
					}
					$newData = new stdClass();
					$newData->nodeId = $nodeId;
					$newData->parentId = $parentId;//$nodeIds[$nodeId]->parentId;
					$newData->title = $title;
					$newData->mdLink = $linkName; 
					$newDoc['pagesByNodeId'][$nodeId] = $newData;
					$newDoc['pagesByLinkName'][$linkName] = $newData;

					continue;	
				}
			}	
		}
	}
	$currentFolder = $originalFolder;
	dsm('current folder:'.$currentFolder.'=====return result:'.json_encode($dataRet));	
	return $dataRet;
}


function mkdoc_book_updateBook($yamlContent, $folder, $gitRepoUrl) {
	$url = 'http://54.69.251.157:6600/updateBook';
	$data = array('name' => 'mkdocs.yml', 'content' => $yamlContent, 'folder' => $folder, 'repourl' => $gitRepoUrl);
	$fieldsData = json_encode($data);
	$header = "Content-type: application/x-www-form-urlencoded\r\n" . "Content-Length: " . strlen($fieldsData) . "\r\n";
	$response = drupal_http_request($url, $header,'POST', $fieldsData);
	dsm($response);


}

function updateMdContent($name, $content, $folder, $gitRepoUrl) {
	$url = 'http://54.69.251.157:6600/updateMdContent';
	$data = array('name' => $name, 'content' => $content, 'folder' => $folder, 'repourl' => $gitRepoUrl);
	$fieldsData = json_encode($data);
	$header = "Content-type: application/x-www-form-urlencoded\r\n" . "Content-Length: " . strlen($fieldsData) . "\r\n";
	$response = drupal_http_request($url, $header,'POST', $fieldsData);
	////dsm($response);


}

function mkdoc_book_menu()
{
	$items = array();
	
	$items['mkdoc_book/new'] = array(
		     'title' => 'gdc book',
			 'page callback' => 'mkdoc_book_new',
			 'access arguments' => array(true),
			 'access callback' => TRUE,
			 'type' => MENU_CALLBACK
			 );
	

	return $items;

}

function mkdoc_book_new() {
	//pass the location of the json file, $_POST will have the value
	var_dump($_POST);
	$GLOBALS["dataFolder"] = $_POST["datafolder"]."/docs/";

	$name = $_POST['name'];
	$bookFolder = $_POST['bookfolder'];	//github folder name
	$dataFolder = $_POST['datafolder']."/docs/";
	$bookId = mkdoc_book_exists($bookFolder);
	var_dump('====*************==========bookid:'.$bookId.'===='.$bookFolder);
	if($bookId) {
		//update current book
		mkdoc_book_refreshBookContent($bookId, $dataFolder, $name);	
//		mkdoc_book_updateBookContent($bookId, $dataFolder);	
	} else {
		//create a book node
		mkdoc_book_createNewBook($name, $bookFolder);
	}
	
    //foreach page
		//create a page node
	return "Im here----".$_POST['name'];	

}

function mkdoc_book_getBookFolder($bookId) {

	$tableName = 'mkdocids';
	if(db_table_exists($tableName)) {
		$query = "select bookfolder,repourl from {$tableName} where bookid=%d";
		$ret = db_query($query, $bookId);

		if(count($ret) > 0) {
			$data = db_fetch_array($ret);

			if($data != FALSE) {
				return array('bookfolder' => $data['bookfolder'], 'repourl' => $data['repourl']);	
			}
		}
	}
	return false;	
}

function mkdoc_book_exists($bookFolder) {
var_dump('====================mkdoc_book_exists');
var_dump($bookFolder);
	$tableName = 'mkdocids';
	if(db_table_exists($tableName)) {
		$query = "select bookid from {$tableName} where bookfolder='%s'";
		$ret = db_query($query, $bookFolder);
var_dump($ret);
		if(count($ret) > 0) {
			$data = db_fetch_array($ret);
var_dump($data);
			if($data) {

				$bookId = $data['bookid'];
				$nodeBook = node_load($bookId);
				if($nodeBook) {
					return $bookId;	
				} else {
					$query = "delete from {$tableName} where bookid=%d";
					$ret = db_query($query, $bookId);
				}
			}
		}
	}
	return false;	
}

class MkDoc
{
	public $siteName;
	public $bookId;
	public $bookFolder;
	public $gitRepoUrl;
	public $pagesByNodeId = array();
	public $pagesByLinkName = array();

	private static $instance = NULL;

	public static function getInstance() {
		if(is_null(self::$instance)) {
			self::$instance = new self();	
		}

		return self::$instance;
	}

	public function getNodeIds() {
		return $this->pagesByNodeId;	
	}

	public function getLinkNames() {
		return $this->pagesByLinkName;	
	}

	public function savePageByNodeId($nodeId, $value) {
		//var_dump( 'save node id:--------'.$nodeId.'--------'.$value);
		$this->pagesByNodeId[$nodeId] = $value;
	}

	public function getPageByNodeId($nodeId) {
		return $this->pagesByNodeId[$nodeId];	
	}

	public function savePageByLinkName($name, $value) {
		//var_dump( '======save link name:'.$name.'---'.$value);
		$this->pagesByLinkName[$name] = $value;
	}

	public function getPageByLinkName($name) {
		return $this->pagesByLinkName[$name];	
	}

	public function getMkdocsFromDb($bookId) {
		$tableName = 'mkdocids';
		if(db_table_exists($tableName)) {
			$query = "select doc from {$tableName} where bookid=%d";
			$ret = db_query($query, $bookId);

			if(count($ret) > 0) {
				$data = db_fetch_array($ret);

				if($data != FALSE) {
					return unserialize($data['doc']);	
				}
			}
		}
	}

	public function setMkdocsToDb($bookId, $value, $bookFolder, $repoUrl) {
		$tableName = 'mkdocids';
		if(!db_table_exists($tableName)) {
			$this->createMkdocTable($tableName);
		}

		$data = serialize(array($bookId => ($value)));
		dsm($data);
		var_dump($data);
		$query = "insert into {$tableName} values(%d, '%s', '%s', '%s') on duplicate key update doc=values(doc),bookfolder=values(bookfolder),repourl=values(repourl)";
		$ret = db_query($query, $bookId, serialize($value), $bookFolder, $repoUrl);
		//$ret = drupal_write_record($tableName, ($data));
		echo '**************drupal_write_record return*********:::' + $ret;
		//var_dump($data);
	}

	public function getNodeIdsFromDb($bookId) {
		
	}

	public function setNodeIdsToDb($bookId, $value) {
		
	}

	private function createMkdocTable($tableName) {
var_dump('------createMkdocTable('.$tableName.')');

		$schema[$table] = array(
			'fields' => array(
				'bookid' => array('type' => 'int', 'not null' => TRUE),
				'doc' => array('type' => 'text'),
				'bookfolder' => array('type' => 'text'),
				'repourl' => array('type' => 'text'),
			),
//			'primary key' => array('bookid'),
		);
$statements = db_create_table_sql($tableName, $schema[$table]);
foreach($statements as $statement) {
	var_dump($statement);	
}
//var_dump( $statements);
echo '<==========>';
$ret = array();
db_create_table($ret, $tableName, $schema[$table]);	
var_dump($ret);

	}
}

function mkdoc_book_updateBookContent($bookId, $dataFolder) {

	$tableName = 'mkdocids';
	$query = "select doc from {$tableName} where bookid=%d";
	$ret = db_query($query, $bookId);

	if(count($ret) > 0) {
		$data = db_fetch_array($ret);

		if($data != FALSE) {
			$mkdoc = unserialize($data['doc']);

			$linkNames = $mkdoc->pagesByLinkName;
////dsm($linkNames);
			foreach($linkNames as $name => $val) {
				//get md file content
				//overwrite page content with node id
				var_dump('updating file '.$dataFolder.$name);
				$file = file_get_contents($dataFolder.$name);
				$node = node_load($val->nodeId);
				$node->body = $file;

				node_save($node);
			}
		}
	}
	
}

//when git files changed
function mkdoc_book_refreshBookContent($bookId, $dataFolder, $yamlName) {
	var_dump('mkdoc_book_refreshBookContent================='.$yamlName);
	
	//travel yaml file all the time, even if the file structure was not changed	
	$tableName = 'mkdocids';
	$query = "select doc from {$tableName} where bookid=%d";
	$ret = db_query($query, $bookId);

	if(count($ret) > 0) {
		$data = db_fetch_array($ret);

		if($data != FALSE) {
			$mkdoc = unserialize($data['doc']);

			$linkNames = $mkdoc->pagesByLinkName;

			$yamlData = mkdoc_book_getYaml($yamlName);

			$bookName = $yamlData['site_name'];
			mkdoc_book_changeBookTitle($bookId, $bookName);
			$mkdoc->siteName = $bookName;
			$yamlPageContent = json_encode($yamlData['pages']);
			$yamlData = json_decode($yamlPageContent, true);

			mkdoc_book_removeMkdocObjPages($mkdoc, $yamlData);
var_dump($mkdoc);
			mkdoc_book_parseYaml($bookId, $yamlData, NULL, $mkdoc);
			
			$bookFolder = $_POST['bookfolder'];
			$repoUrl = $_POST['gitrepourl'];

			$mkdoc->setMkdocsToDb($bookId,$mkdoc, $bookFolder, $repoUrl);
		}
	}
	
}

function mkdoc_book_changeBookTitle($bookId, $title) {
	
	$node = node_load($bookId);
	if($node) {
		$node->title = $title;

		node_save($node);
	}
}

function mkdoc_book_getYaml($name) {

	$file = file_get_contents($name);
	$data = json_decode(($file), true);

	return $data;
}

function mkdoc_book_removeMkdocObjPages(&$mkdoc, $yamlPages) {
	
	$linkNames = $mkdoc->pagesByLinkName;
	$nodeIds = $mkdoc->pagesByNodeId;
	$yamlStr = json_encode($yamlPages, JSON_UNESCAPED_SLASHES);

	var_dump($yamlStr);

	foreach($linkNames as $name => $node) {
		
		//$name-----"A/a1.md"
		$nodeId = $node->nodeId;
		//var_dump($name.'--------'.$nodeId);
		if(strpos($yamlStr, $name) === false) {//not found, remove it
			unset($linkNames[$name]);
			unset($nodeIds[$nodeId]);
			mkdoc_book_deleteNode($nodeId);

			var_dump('removed page========>'.$name.'===='.$nodeId);
		}
	}

	$mkdoc->pagesByLinkName = $linkNames;
	$mkdoc->pagesByNodeId = $nodeIds;

}

function mkdoc_book_deleteNode($nodeId) {
	
	global $user;
	$currentUser = $user;
	$user = user_load(1);

	node_delete($nodeId);

	$user = $currentUser;

}

function mkdoc_book_parseYaml($bookNodeId, $obj, $parentId, &$mkdoc) {
	echo "=================";
var_dump($obj);

	foreach($obj as $chapter => $chapterValue) {

var_dump($chapter);
		echo "***********";
		var_dump($chapterValue);

echo "----------------CHAPTER---".$chapter."----------------".is_array($chapterValue).'======'.$parentId;
		if(is_array($chapterValue)) {
			$saveObj = new stdClass();
			$saveObj->parentId = $parentId;
			
			if(array_key_exists($chapter, $mkdoc->pagesByLinkName)) {
				
				$linkNames = $mkdoc->pagesByLinkName;
				$parentId = $linkNames[$chapter]->nodeId;
				mkdoc_book_parseYaml($bookNodeId, $chapterValue, $parentId, $mkdoc);
				
			} else {
				
				$newNodeId = createPageNodeEx($bookNodeId,$parentId, $chapter, $chapter);
				dsm($newNodeId.'------'.$chapter);
				$saveObj->nodeId = $newNodeId;
				$saveObj->title = $chapter;
				$mkdoc->savePageByNodeId($newNodeId, $saveObj);
				
				mkdoc_book_parseYaml($bookNodeId, $chapterValue, $newNodeId, $mkdoc);	
			}

		} else {

			$attr = is_object($chapterValue) ? get_object_vars($chapterValue) : $chapterValue;

			foreach($attr as $key => $val) {
				var_dump($key.'------'.$val.'-------is md link:'.isMdLink($val));
				
				if(is_array($val)) {
					$saveObj = new stdClass();
					$saveObj->parentId = $parentId;
					
					if(array_key_exists($key, $mkdoc->pagesByLinkName)) {
						
						$linkNames = $mkdoc->pagesByLinkName;
						$parentId = $linkNames[$key]->nodeId;
						mkdoc_book_parseYaml($bookNodeId, $val, $parentId, $mkdoc);
						
					} else {
						$parentId = createPageNodeEx($bookNodeId,$parentId, $key, $key);
						$saveObj->nodeId = $parentId;
						$saveObj->mdLink = $val;
						$saveObj->title = $key;
						$mkdoc->savePageByNodeId($parentId, $saveObj);

						mkdoc_book_parseYaml($bookNodeId, $val, $parentId, $mkdoc);	
					}
				} else {

				
					$saveObj = new stdClass();
					$saveObj->parentId = $parentId;

					if(isMdLink($val)) {
						$folder = $GLOBALS["dataFolder"].$val;
						echo "*************md link********".$folder;
						$linkNames = $mkdoc->pagesByLinkName;
						var_dump('array_key_exists($linkNames, $val)==='.$val.'======='.array_key_exists($val, $linkNames));

						if(array_key_exists($val, $linkNames)) {
							$nodeId = $linkNames[$val]->nodeId;
							refreshPageNode($nodeId, $parentId, $key, $val, $folder);	
						} else {
							$nodeId = createPageNode($bookNodeId, $parentId, $key, $val, $folder);	
						}

					} else {

						$linkNames = $mkdoc->pagesByLinkName;

						if(array_key_exists($val, $linkNames)) {
							$nodeId = $linkNames[$val]->nodeId;
							refreshPageNodeEx($nodeId, $parentId, $key, $key);
						} else {
							$nodeId = createPageNodeEx($bookNodeId, $parentId, $key, $key);	
						}
					}

					$saveObj->nodeId = $nodeId;
					$saveObj->title = $key;
					$saveObj->mdLink = $val;
					$mkdoc->savePageByNodeId($nodeId, $saveObj);
					$mkdoc->savePageByLinkName($val, $saveObj);
				}
			}
		}
			
	}
	
}

function mkdoc_book_createNewBook($name) {
	$file = file_get_contents($name);
	//var_dump($file);
	//var_dump(base64_decode($file));
	//$data = json_decode(base64_decode($file), true);
	$data = json_decode(($file), true);
	var_dump($data);
	$bookFolder = $_POST['bookfolder'];
	$repoUrl = $_POST['gitrepourl'];

	createBookNode($bookFolder, $repoUrl, $data);
}

function createBookNode($bookFolder, $repoUrl, $data) {
	
	$node = new stdClass();
	$node->book = array('bid'=>'new');
	
	$node->name = $data['site_name']; 
	$node->title = $node->name; 
	//$node->body = json_encode($data['pages']); 
	$node->type = 'book';
	$node->created = time(); 
	$node->changed = $node->created; 
	$node->promote = 0; 
	$node->sticky = 0; 
	$node->format = 2;
	$node->status = 1;
	$node->language = 'en';

	node_save($node);
	$bookNodeId = $node->nid;

	mkdoc_book_saveBookFolderToDb($bookFolder, $repoUrl, $bookNodeId);

	$mkdoc = MkDoc::getInstance();
	$mkdoc->siteName = $node->name;
	$mkdoc->bookId = $bookNodeId;
	$mkdoc->gitRepoUrl = $repoUrl;
	$mkdoc->bookFolder = $bookFolder;

	$GLOBALS['bookNodeId'] = $bookNodeId;

	$yamlPageContent = json_encode($data['pages']);
	//createNewPage($bookNodeId, $yamlPageContent);
	createNewPageEx($bookNodeId, $bookFolder, $repoUrl, $yamlPageContent);
}

function mkdoc_book_saveBookFolderToDb($bookFolder, $repoUrl, $bookNodeId) {
	
}

function createNewPageEx($bookNodeId, $bookFolder, $repoUrl, $yamlPageContent) {
	$yamlObj = json_decode($yamlPageContent);

	parseObject($bookNodeId, $yamlObj, NULL);

	$mkdoc = MkDoc::getInstance();
	$mkdoc->setMkdocsToDb($bookNodeId,$mkdoc, $bookFolder, $repoUrl);
	//var_dump($mkdoc);
	echo '*********after parseObject'.$bookNodeId;
	$datamk = $mkdoc->getMkdocsFromDb($bookNodeId);
	
	//var_dump($datamk->pagesByLinkName);
	//var_dump($docmk->pagesByLinkName['index.md']);
}

function parseObject($bookNodeId, $obj, $parentId) {
	echo "=================";
var_dump($obj);	
	$mkdoc = MkDoc::getInstance();
	foreach($obj as $chapter => $chapterValue) {

//var_dump($chapter);
		//echo "***********";
		//var_dump($chapterValue);

echo "----------------CHAPTER---".$chapter."----------------".is_array($chapterValue).'======';
		if(is_array($chapterValue)) {
			$saveObj = new stdClass();
			$saveObj->parentId = $parentId;
			
			$newNodeId = createPageNodeEx($bookNodeId,$parentId, $chapter, $chapter);
			$saveObj->nodeId = $newNodeId;
			$saveObj->title = $chapter;
			$mkdoc->savePageByNodeId($newNodeId, $saveObj);
			//$mkdoc->savePageByLinkName($chapter, $saveObj);

			parseObject($bookNodeId, $chapterValue, $newNodeId);	
		} else {

			$attr = is_object($chapterValue) ? get_object_vars($chapterValue) : $chapterValue;

			foreach($attr as $key => $val) {
				var_dump($key.'-------------is md link:'.isMdLink($val));
				
				if(is_array($val)) {
					$saveObj = new stdClass();
					$saveObj->parentId = $parentId;
					
					$parentId = createPageNodeEx($bookNodeId,$parentId, $key, $key);
					$saveObj->nodeId = $parentId;
					$saveObj->mdLink = $val;
					$saveObj->title = $key;
					$mkdoc->savePageByNodeId($parentId, $saveObj);
					$mkdoc->savePageByLinkName($key, $saveObj);

					parseObject($bookNodeId, $val, $parentId);	
				} else {

				
					$saveObj = new stdClass();
					$saveObj->parentId = $parentId;

					if(isMdLink($val)) {
						$folder = $GLOBALS["dataFolder"].$val;
//						echo "*************md link********".$folder;
						$nodeId = createPageNode($bookNodeId, $parentId, $key, $val, $folder);	

					} else {

						$nodeId = createPageNodeEx($bookNodeId, $parentId, $key, $key);
					}

					$saveObj->nodeId = $nodeId;
					$saveObj->title = $key;
					$saveObj->mdLink = $val;
					$mkdoc->savePageByNodeId($nodeId, $saveObj);
					$mkdoc->savePageByLinkName($val, $saveObj);
				}
			}
		}
			
	}
	
}

function isMdLink($link) {
	return preg_match('/([^"]*\.md)/', $link) > 0;	
}

function getNodeId($matches) {
   //echo '=================';
   $matches[0] = str_replace('\\', '', $matches[0]);
   $matches[1] = str_replace('\\', '', $matches[1]);
//   var_dump($matches);
	$folder = $GLOBALS["dataFolder"].$matches[1];
//	print( $folder);

	$nid = createPageNode($GLOBALS['bookNodeId'], $matches[1], $folder);
	$matches[0] = "node/".$nid;
	$hrefa = "<a href=".$matches[0].">".$matches[1]."</a>";
	return $hrefa;
}

function createNewPage($bookId, $file) {
	//$file = file_get_contents($name);
	//var_dump($file);

    //$ret = preg_replace_callback('/"([^"]*\.md)"/', "getNodeId", $file);
	

    $ret = preg_replace_callback('/"([^"]*\.md)"/', function($matches) {
		
		$matches[0] = str_replace('\\', '', $matches[0]);
		$matches[1] = str_replace('\\', '', $matches[1]);
		//var_dump($matches);
		$folder = $GLOBALS["dataFolder"].$matches[1];
		//print( $folder);

		$nid = createPageNode($bookId, $matches[1], $folder);
	
		savePageInfo($bookId, $nid, $name);

		$matches[0] = "node/".$nid;
		$hrefa = "<a href=".$matches[0].">".$matches[1]."</a>";
		return $hrefa;
	

	}, $file);
	
	var_dump($ret);
	
	//updateBookNode($bookId, $ret);

}

function savePageInfo($bookId, $nid, $name) {
	
}

function createPageNodeEx($bookId, $parentId, $title, $content) {
	var_dump('createPageNodeEx---'.$title);
	if($bookId === NULL) {
		$bookId = 'new';	
	}
	$node = new stdClass();
	$node->book = array('bid'=>$bookId);
	$node->name = $title; 
	$node->title = $node->name; 
	$node->body = $content; 
	$node->type = 'page'; 
	if($parentId !== NULL) {
		//$nodeParent = node_load($parentId);
		//$node->book['plid'] = $nodeParent->book['mlid'];
		//$node->parent = $parentId;
		//$node->book['plid'] = $parentId;
	}
	$node->created = time(); 
	$node->changed = $node->created; 
	$node->promote = 0; 
	$node->sticky = 0; 
	$node->format = 2;
	$node->status = 1;
	$node->language = 'en'; 
/*
	$plid = _nodehierarchy_get_node_mlid($parentId,true);
	$nodehierarchy_menu_links = _nodehierarchy_default_menu_link($parentId, $plid);
	$nodehierarchy_menu_links['pnid']=$parentId;
	$nodehierarchy_menu_links['hidden'] = FALSE;
	$nodehierarchy_menu_links['enabled'] = TRUE;
	$node->nodehierarchy_menu_links[] = $nodehierarchy_menu_links;
*/

	node_save($node);
	echo "----------------".$node->nid;
	if($parentId !== NULL) {
		//$node->parent = $parentId;
		//$nodeParent = node_load($parentId);
		//$node->book['plid'] = $nodeParent->book['mlid'];
		//$node->book['mlid'] = $parentId;
		//node_save($node);
		//_book_update_outline($node);
	}
	//echo 'return book update#######'._book_update_outline($node);

	return $node->nid;

}

function refreshPageNodeEx($nodeId, $parentId, $title, $content) {
	var_dump('refreshPageNodeEx----'.$nodeId);

	$node->name = $title; 
	$node->title = $node->name; 
	$node->body = $content; 
	
	node_save($node);
}

function refreshPageNode($nodeId, $parentId, $title, $fileName, $fileNameWithFolder) {
	var_dump('refreshPageNode----'.$nodeId.'----parentId---'.$parentId);
	if(!$nodeId) {
		return;	
	}
	$node = node_load($nodeId);
	$filemd = file_get_contents($fileNameWithFolder);

	$node->name = $title; 
	$node->title = $node->name; 
	$node->body = $filemd; 

	if($parentId !== NULL) {
		$nodeParent = node_load($parentId);
		$node->book['plid'] = $nodeParent->book['mlid'];


		$node->book['bid'] = $nodeParent->book['bid'];
		$node->book['plid'] = $nodeParent->book['mlid'];
		$node->book['menu_name'] = $nodeParent->book['menu_name'];
	}

	node_save($node);
}

function createPageNode($bookId, $parentId, $title, $fileName, $fileNameWithFolder) {
	var_dump('createPageNode----'.$title);
	echo $fileName;
	$filemd = file_get_contents($fileNameWithFolder);
//	echo "================";
	echo ('parentId:'.$parentId);
	//var_dump(node_load($bookId));
//	echo "================";
	//var_dump(node_load($parentId));

	if($bookId === NULL) {
		$bookId = 'new';	
	}
	$node = new stdClass();
	$node->book = array('bid'=>$bookId);
	$node->name = $title; 
	$node->title = $node->name; 
	$node->body = $filemd; 
	$node->type = 'page'; //or ‘page’
	if($parentId !== NULL) {
		$nodeParent = node_load($parentId);

		$node->book['bid'] = $nodeParent->book['bid'];
		$node->book['plid'] = $nodeParent->book['mlid'];
		$node->book['menu_name'] = $nodeParent->book['menu_name'];
	}
	$node->created = time(); 
	$node->changed = $node->created; 
	$node->promote = 0; 
	$node->sticky = 0; 
	$node->format = 2;
	$node->status = 1;
	$node->language = 'en'; 

	node_save($node);
	echo "----------------".$node->nid;
/*	if($parentId !== NULL) {
		$node->parent = $parentId;
		$nodeParent = node_load($parentId);
		$node->book['plid'] = $nodeParent->book['mlid'];
		//$node->book['mlid'] = $parentId;

		$node->book['bid'] = $nodeParent->book['bid'];
		$node->book['plid'] = $nodeParent->book['mlid'];
		$node->book['menu_name'] = $nodeParent->book['menu_name'];
		node_save($node);
		_book_update_outline($node);
	}
*/
	return $node->nid;

}

function updateBookNode($bookId, $content) {

	$node = node_load($bookId);

	
	$node->body = $content; 
	$node->changed = $node->created; 

	node_save($node);
	
}



