<?php 


/**
 * Implementation of hook_filter()
 */
function mkdoc_nid_filter($op, $delta = 0, $format = -1, $text = '') {
  dsm('******************mkdoc_filter*****');
  dsm($op);
  switch ($op) {
  case 'list':
    return array(0 => t('Insert node'));

  case 'description':
    return t('By including the syntax [[nid:(node_id)]], this filter will embed the node with given NID');

  case 'prepare':
    return $text;

  case 'no cache':
    return TRUE;

  case "process":
    // replace on [[nid: ###]]
    return preg_replace_callback('/([^"]*\.md)/', function($matches) {
		
		dsm($matches);
		$output = '<a href="node/888">'.$matches[0].'</a>';

		return $output;
		
	}, $text);
  }
}

/**
 * Implementation of hook_filter_tips()
 */
function mkdoc_nid_filter_tips($delta, $format, $long = FALSE) {
  return t('[[nid:123]] - insert a node content');
}

function mkdoc_nid_init() {
	dsm('mkdoc_nid_init');	
}

function mkdoc_nid_preprocess_node() {
	dsm('mkdoc_nid_preprocess_node');	
}

